# -*- coding: utf-8 -*-
"""image uniformity analyze

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9Mxq_fEnnSbKq_kqBb0zv8Vfwq5TnvP
"""

import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import gc
from pathlib import Path
from google.colab import files
from google.colab import drive
import zipfile
import shutil
import os
import random

# 0. Google Drive 연결


drive.mount("/content/drive")

# ============================================================
# 0. 라이브러리 설치 및 불러오기
# ============================================================

!pip install openpyxl -q

import os
import re
import cv2
import zipfile
import shutil
import gc
import numpy as np
import pandas as pd

from pathlib import Path


# ============================================================
# 1. 이미지 폴더 또는 zip 파일 경로 설정
# ============================================================

# zip 파일이면 zip 경로를 넣고,
# 이미 압축이 풀린 이미지 폴더면 폴더 경로를 넣어도 됨.
ZIP_OR_FOLDER_PATH = "/content/drive/MyDrive/BO3_circle_crop"

# zip을 풀 임시 폴더
IMAGE_DIR = Path("/content/fluorescence_images")

# 결과 저장 폴더
OUTPUT_DIR = Path("/content/ring_green_intensity_output")


# ============================================================
# 2. 기존 임시 폴더 삭제 후 새로 만들기
# ============================================================

if IMAGE_DIR.exists():
    shutil.rmtree(IMAGE_DIR)

if OUTPUT_DIR.exists():
    shutil.rmtree(OUTPUT_DIR)

IMAGE_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# 3. zip 압축 해제 또는 이미지 폴더 사용
# ============================================================

source_path = Path(ZIP_OR_FOLDER_PATH)

if not source_path.exists():
    raise FileNotFoundError(f"경로를 찾을 수 없습니다: {source_path}")

if source_path.is_file() and zipfile.is_zipfile(source_path):
    with zipfile.ZipFile(source_path, "r") as zip_ref:
        zip_ref.extractall(IMAGE_DIR)

    print("압축 해제 완료")
    print("IMAGE_DIR:", IMAGE_DIR)

elif source_path.is_dir():
    IMAGE_DIR = source_path

    print("이미 압축이 풀린 이미지 폴더를 사용합니다.")
    print("IMAGE_DIR:", IMAGE_DIR)

else:
    raise ValueError("입력한 경로가 zip 파일도 아니고 이미지 폴더도 아닙니다.")

print("OUTPUT_DIR:", OUTPUT_DIR)


# ============================================================
# 4. 이미지 파일 찾기
# ============================================================

image_files = []

extensions = [
    "*.jpg", "*.jpeg", "*.JPG", "*.JPEG",
    "*.png", "*.PNG",
    "*.tif", "*.tiff", "*.TIF", "*.TIFF",
    "*.bmp", "*.BMP"
]

for ext in extensions:
    image_files.extend(list(IMAGE_DIR.rglob(ext)))

image_files = [
    f for f in image_files
    if not f.name.startswith(".") and "__MACOSX" not in str(f)
]

image_files = sorted(image_files)

print("발견된 이미지 개수:", len(image_files))

if len(image_files) == 0:
    raise ValueError("이미지 파일을 찾지 못했습니다.")

print("처음 10개 이미지 파일:")
for f in image_files[:10]:
    print(f)


# ============================================================
# 5. 파일명에서 rpm, 시간, 농도, 반복번호 추출
# ============================================================

def parse_filename_condition(image_path):
    """
    파일명 예시:
    500 10 4 1_circle_crop.png

    의미:
    rpm = 500
    time = 10
    concentration = 4
    repeat = 1
    """

    stem = Path(image_path).stem

    cleaned = stem.replace("_circle_crop", "")
    cleaned = cleaned.replace("circle_crop", "")

    numbers = re.findall(r"\d+", cleaned)

    if len(numbers) < 4:
        raise ValueError(
            f"파일명에서 rpm, 시간, 농도, 반복번호를 읽을 수 없습니다: {Path(image_path).name}"
        )

    rpm = int(numbers[0])
    time = int(numbers[1])
    concentration = int(numbers[2])
    repeat = int(numbers[3])

    return rpm, time, concentration, repeat


# ============================================================
# 6. 이미지 1장에 대해 고리별 green_intensity 평균 계산
# ============================================================

def calculate_ring_mean_green_intensity(image_path):
    image_path = Path(image_path)

    # 한글 경로도 읽을 수 있도록 처리
    img_array = np.fromfile(str(image_path), np.uint8)
    img_bgr = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

    if img_bgr is None:
        raise ValueError(f"이미지를 읽을 수 없습니다: {image_path}")

    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # Green 채널 추출
    G = img_rgb[:, :, 1]

    # 이미지 중심을 원의 중심으로 설정
    height, width = G.shape
    x_center = width // 2
    y_center = height // 2

    radius = min(
        x_center,
        y_center,
        width - 1 - x_center,
        height - 1 - y_center
    )

    edge_exclusion_ratio = 1.00
    sample_radius = radius * edge_exclusion_ratio

    # 고리 설정
    num_rings = 100

    ring_mean_results = []

    for ring in range(1, num_rings + 1):
        # 기존 방식 유지:
        # 가장자리로 갈수록 고리 면적이 커지므로 점 개수를 증가시킴
        points_in_this_ring = 10 * (2 * ring - 1)

        # 각 고리의 가운데 반지름 위치
        r_norm = (ring - 0.5) / num_rings
        r = sample_radius * r_norm

        intensities = []

        for j in range(points_in_this_ring):
            theta = 2 * np.pi * j / points_in_this_ring

            # 고리마다 각도를 살짝 회전시켜 점들이 일직선으로 겹쳐 보이는 것 방지
            theta += ring * np.pi / points_in_this_ring

            x = int(round(x_center + r * np.cos(theta)))
            y = int(round(y_center + r * np.sin(theta)))

            x = np.clip(x, 0, width - 1)
            y = np.clip(y, 0, height - 1)

            intensities.append(float(G[y, x]))

        mean_green_intensity = np.mean(intensities)

        ring_mean_results.append({
            "ring": ring,
            "r_norm": r_norm,
            "points_in_ring": points_in_this_ring,
            "mean_green_intensity": mean_green_intensity
        })

    ring_mean_df = pd.DataFrame(ring_mean_results)

    rpm, time, concentration, repeat = parse_filename_condition(image_path)

    ring_mean_df.insert(0, "filename", image_path.name)
    ring_mean_df.insert(1, "rpm", rpm)
    ring_mean_df.insert(2, "time", time)
    ring_mean_df.insert(3, "concentration", concentration)
    ring_mean_df.insert(4, "repeat", repeat)

    return ring_mean_df


# ============================================================
# 7. 전체 이미지에 대해 고리별 green_intensity 평균 계산
# ============================================================

all_ring_mean_results = []

for idx, image_path in enumerate(image_files, start=1):
    print(f"[{idx}/{len(image_files)}] 분석 중: {Path(image_path).name}")

    try:
        ring_mean_df = calculate_ring_mean_green_intensity(image_path)
        all_ring_mean_results.append(ring_mean_df)

    except Exception as e:
        print(f"오류 발생: {Path(image_path).name}")
        print(e)

    gc.collect()


# ============================================================
# 8. 전체 결과 DataFrame 생성
# ============================================================

all_ring_mean_df = pd.concat(all_ring_mean_results, ignore_index=True)

all_ring_mean_df = all_ring_mean_df.sort_values(
    by=["rpm", "time", "concentration", "repeat", "ring"]
).reset_index(drop=True)

print()
print("전체 이미지의 고리별 green_intensity 평균:")
display(all_ring_mean_df)


# ============================================================
# 9. 같은 조건의 반복 실험끼리 고리별 평균 계산
# ============================================================

# 같은 rpm, time, concentration, ring에 대해
# repeat 1, 2, 3의 mean_green_intensity를 평균냄

condition_ring_mean_df = (
    all_ring_mean_df
    .groupby(["rpm", "time", "concentration", "ring"], as_index=False)
    .agg(
        repeat_count=("repeat", "count"),
        repeats=("repeat", lambda x: ",".join(map(str, sorted(x)))),
        mean_green_intensity=("mean_green_intensity", "mean"),
        std_green_intensity=("mean_green_intensity", lambda x: x.std(ddof=0)),
        points_in_ring=("points_in_ring", "mean"),
        r_norm=("r_norm", "mean"),
        filenames=("filename", lambda x: " / ".join(x))
    )
)

condition_ring_mean_df = condition_ring_mean_df.sort_values(
    by=["rpm", "time", "concentration", "ring"]
).reset_index(drop=True)

print()
print("조건별 반복 평균 고리별 green_intensity:")
display(condition_ring_mean_df)


# ============================================================
# 10. 엑셀 파일로 저장
# ============================================================

output_excel_path = OUTPUT_DIR / "ring_mean_green_intensity_results.xlsx"

with pd.ExcelWriter(output_excel_path, engine="openpyxl") as writer:
    all_ring_mean_df.to_excel(
        writer,
        sheet_name="image_each_ring_mean",
        index=False
    )

    condition_ring_mean_df.to_excel(
        writer,
        sheet_name="condition_ring_mean",
        index=False
    )

print()
print("저장 완료")
print(f"엑셀 저장 위치: {output_excel_path}")


# ============================================================
# 11. 엑셀 파일 다운로드
# ============================================================

files.download(str(output_excel_path))