# -*- coding: utf-8 -*-
"""image circle crop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOrZ2oSo92Y-7GngV76okcgl7WXLuKzi
"""

from google.colab import drive
drive.mount('/content/drive')

"""/content/drive/MyDrive/2026 전람회 - spin coating/2026 전람회 - 박막 형광 현미경 data.zip"""

import zipfile
import shutil
import os
import gc
from pathlib import Path

ZIP_PATH = "/content/drive/MyDrive/2026 전람회 - spin coating/data/BO1_(1).zip"

IMAGE_DIR = Path("/content/fluorescence_images")
OUTPUT_DIR = Path("/content/fluorescence_circle_output")

if IMAGE_DIR.exists():
    shutil.rmtree(IMAGE_DIR)

if OUTPUT_DIR.exists():
    shutil.rmtree(OUTPUT_DIR)

IMAGE_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
    zip_ref.extractall(IMAGE_DIR)

print("압축 해제 완료")
print("IMAGE_DIR:", IMAGE_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)

image_files = []

extensions = [
    "*.jpg", "*.jpeg", "*.JPG", "*.JPEG",
    "*.png", "*.PNG",
    "*.tif", "*.tiff", "*.TIF", "*.TIFF"
]

for ext in extensions:
    image_files.extend(list(IMAGE_DIR.rglob(ext)))

image_files = sorted(image_files)

print("발견된 이미지 개수:", len(image_files))

for f in image_files[:10]:
    print(f)

import cv2
import numpy as np
import pandas as pd
from pathlib import Path
from tqdm import tqdm
import shutil
import gc
from google.colab import files
from IPython.display import display, Image

# 형광 영역 검출 기준
# 원이 너무 작게 잡히면 0.04
# 배경까지 잡히면 0.08~0.10
THRESHOLD_RATIO = 0.06

# edge bead 포함 → 최대 내접원 전체 사용
RADIUS_RATIO = 0.95

# 중심-가장자리 비교용
CENTER_RATIO = 0.30
EDGE_INNER_RATIO = 0.75

# RAM 절약을 위해 1/8 크기로 읽기
# 너무 작게 보이면 cv2.IMREAD_REDUCED_COLOR_4 로 변경 가능
READ_MODE = cv2.IMREAD_REDUCED_COLOR_8

# 너무 작은 잡음 제거 기준
MIN_AREA = 300

# JPG 8-bit 포화 기준
SATURATION_VALUE = 250

# 한 번에 처리할 이미지 개수
BATCH_SIZE = 3

def read_image_lowram(image_path):
    """
    JPG 이미지를 축소해서 읽어 RAM 사용량을 줄인다.
    """
    img = cv2.imread(str(image_path), READ_MODE)

    if img is None:
        raise ValueError("이미지를 읽을 수 없습니다.")

    return img


def extract_green_channel(img):
    """
    형광 이미지의 green channel 추출.
    OpenCV는 BGR 순서이므로 index 1이 green.
    """
    if img.ndim == 2:
        return img
    return img[:, :, 1]


def detect_main_circle(img):
    """
    형광 영역에서 최대 내접원을 검출한다.
    이 원은 주 박막 영역을 대표한다.
    """

    green = extract_green_channel(img)
    h, w = green.shape

    blurred = cv2.GaussianBlur(green, (5, 5), 0)

    max_val = float(np.max(blurred))
    if max_val <= 0:
        raise ValueError("이미지 밝기값이 0입니다.")

    threshold_value = THRESHOLD_RATIO * max_val
    binary = (blurred > threshold_value).astype(np.uint8)

    kernel = np.ones((5, 5), np.uint8)
    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)
    binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)

    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(binary)

    if num_labels <= 1:
        raise ValueError("형광 영역 검출 실패. THRESHOLD_RATIO를 낮춰보세요.")

    areas = stats[1:, cv2.CC_STAT_AREA]
    largest_label = 1 + int(np.argmax(areas))
    largest_area = float(np.max(areas))

    if largest_area < MIN_AREA:
        raise ValueError("검출된 형광 영역이 너무 작습니다.")

    film_mask = (labels == largest_label).astype(np.uint8)

    # distance transform으로 최대 내접원 검출
    dist = cv2.distanceTransform(film_mask, cv2.DIST_L2, 5)
    _, max_dist, _, max_loc = cv2.minMaxLoc(dist)

    cx, cy = max_loc
    R_detected = float(max_dist)
    R_analysis = float(RADIUS_RATIO * R_detected)

    if R_detected <= 3:
        raise ValueError("검출된 반지름이 너무 작습니다.")

    return green, film_mask, cx, cy, R_detected, R_analysis, threshold_value


def make_circle_mask(shape, cx, cy, R):
    """
    원형 mask 생성.
    """
    h, w = shape
    mask = np.zeros((h, w), dtype=np.uint8)
    cv2.circle(mask, (int(cx), int(cy)), int(R), 1, -1)
    return mask


def crop_square_around_circle(img, mask, cx, cy, R):
    """
    원 주변을 정사각형으로 crop하고,
    원 바깥은 검은색으로 처리한다.
    """

    h, w = mask.shape
    R_int = int(np.ceil(R))

    x1 = int(cx - R_int)
    x2 = int(cx + R_int)
    y1 = int(cy - R_int)
    y2 = int(cy + R_int)

    # 이미지 밖으로 나가는 경우 padding
    pad_left = max(0, -x1)
    pad_top = max(0, -y1)
    pad_right = max(0, x2 - w)
    pad_bottom = max(0, y2 - h)

    if pad_left > 0 or pad_top > 0 or pad_right > 0 or pad_bottom > 0:
        img_padded = cv2.copyMakeBorder(
            img,
            pad_top,
            pad_bottom,
            pad_left,
            pad_right,
            borderType=cv2.BORDER_CONSTANT,
            value=(0, 0, 0)
        )

        mask_padded = cv2.copyMakeBorder(
            mask,
            pad_top,
            pad_bottom,
            pad_left,
            pad_right,
            borderType=cv2.BORDER_CONSTANT,
            value=0
        )

        x1 += pad_left
        x2 += pad_left
        y1 += pad_top
        y2 += pad_top

    else:
        img_padded = img
        mask_padded = mask

    crop_img = img_padded[y1:y2, x1:x2].copy()
    crop_mask = mask_padded[y1:y2, x1:x2].copy()

    # 원 바깥 검은색 처리
    circle_img = np.zeros_like(crop_img)
    circle_img[crop_mask == 1] = crop_img[crop_mask == 1]

    return circle_img, crop_mask


def calculate_metrics(green, film_mask, cx, cy, R):
    """
    원형 영역 전체를 대상으로 균일도 지표 계산.
    edge bead가 원 안에 있으면 포함된다.
    """

    h, w = green.shape

    circle_mask = make_circle_mask((h, w), cx, cy, R)

    center_mask = make_circle_mask((h, w), cx, cy, CENTER_RATIO * R)

    outer_mask = make_circle_mask((h, w), cx, cy, R)
    inner_edge_mask = make_circle_mask((h, w), cx, cy, EDGE_INNER_RATIO * R)
    edge_mask = outer_mask - inner_edge_mask

    green_float = green.astype(np.float32)

    circle_values = green_float[circle_mask == 1]
    center_values = green_float[center_mask == 1]
    edge_values = green_float[edge_mask == 1]
    total_values = green_float[film_mask == 1]

    mean_circle = float(np.mean(circle_values))
    std_circle = float(np.std(circle_values))
    CV_circle = float(std_circle / mean_circle) if mean_circle > 0 else np.nan

    mean_center = float(np.mean(center_values))
    mean_edge = float(np.mean(edge_values))
    RNU_circle = float(abs(mean_center - mean_edge) / mean_circle) if mean_circle > 0 else np.nan

    mean_total = float(np.mean(total_values))
    CV_total_fluorescence = float(np.std(total_values) / mean_total) if mean_total > 0 else np.nan

    # edge bead가 강하면 보통 edge 평균이 center보다 커짐
    EBI = float((mean_edge - mean_center) / mean_circle) if mean_circle > 0 else np.nan

    A_total = float(np.sum(film_mask))
    A_circle = float(np.pi * R**2)
    protrusion_ratio = float((A_total - A_circle) / A_circle) if A_circle > 0 else np.nan

    saturation_ratio = float(np.sum(circle_values >= SATURATION_VALUE) / len(circle_values))

    # edge bead 포함 목적 함수
    # 원 안 전체의 불균일도 중심으로 평가
    J_objective = float(
        0.60 * CV_circle
        + 0.25 * RNU_circle
        + 0.15 * max(protrusion_ratio, 0)
    )

    metrics = {
        "mean_circle": mean_circle,
        "std_circle": std_circle,
        "CV_circle": CV_circle,
        "mean_center": mean_center,
        "mean_edge": mean_edge,
        "RNU_circle": RNU_circle,
        "EBI": EBI,
        "CV_total_fluorescence": CV_total_fluorescence,
        "protrusion_ratio": protrusion_ratio,
        "saturation_ratio_circle": saturation_ratio,
        "J_objective": J_objective
    }

    del circle_values, center_values, edge_values, total_values
    del circle_mask, center_mask, outer_mask, inner_edge_mask, edge_mask
    gc.collect()

    return metrics


def process_one_image_circle(image_path, save_dir):
    """
    이미지 1장을 분석하고,
    원형 crop 이미지와 overlay 이미지를 저장한다.
    """

    image_path = Path(image_path)
    save_dir = Path(save_dir)

    circle_dir = save_dir / "circle_crops"
    overlay_dir = save_dir / "overlay_check"

    circle_dir.mkdir(parents=True, exist_ok=True)
    overlay_dir.mkdir(parents=True, exist_ok=True)

    img = read_image_lowram(image_path)

    green, film_mask, cx, cy, R_detected, R_analysis, threshold_value = detect_main_circle(img)

    circle_mask = make_circle_mask(green.shape, cx, cy, R_analysis)

    metrics = calculate_metrics(
        green=green,
        film_mask=film_mask,
        cx=cx,
        cy=cy,
        R=R_analysis
    )

    # 원형 crop 이미지 저장
    circle_img, crop_mask = crop_square_around_circle(
        img=img,
        mask=circle_mask,
        cx=cx,
        cy=cy,
        R=R_analysis
    )

    circle_path = circle_dir / f"{image_path.stem}_circle_crop.png"
    cv2.imwrite(str(circle_path), circle_img)

    # overlay 이미지 저장
    overlay = img.copy()

    # 파란색: 최대 내접원 전체, edge bead 포함 분석 원
    cv2.circle(overlay, (int(cx), int(cy)), int(R_analysis), (255, 0, 0), 2)

    # 노란색: 중심점
    cv2.circle(overlay, (int(cx), int(cy)), 4, (0, 255, 255), -1)

    text1 = f"CV={metrics['CV_circle']:.4f}, RNU={metrics['RNU_circle']:.4f}"
    text2 = f"J={metrics['J_objective']:.4f}, EBI={metrics['EBI']:.4f}"

    cv2.putText(
        overlay,
        text1,
        (20, 40),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (255, 255, 255),
        2,
        cv2.LINE_AA
    )

    cv2.putText(
        overlay,
        text2,
        (20, 80),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (255, 255, 255),
        2,
        cv2.LINE_AA
    )

    overlay_path = overlay_dir / f"{image_path.stem}_overlay.png"
    cv2.imwrite(str(overlay_path), overlay)

    result = {
        "filename": image_path.name,
        "path": str(image_path),
        "width_reduced_px": int(green.shape[1]),
        "height_reduced_px": int(green.shape[0]),
        "center_x": int(cx),
        "center_y": int(cy),
        "R_detected_px": float(R_detected),
        "R_analysis_px": float(R_analysis),
        "threshold_ratio": THRESHOLD_RATIO,
        "threshold_value": float(threshold_value),
        "circle_crop_path": str(circle_path),
        "overlay_path": str(overlay_path),
        **metrics
    }

    del img, green, film_mask, circle_mask, circle_img, crop_mask, overlay
    gc.collect()

    return result


def run_batch(start, end):
    """
    start부터 end-1까지 처리.
    RAM 문제를 줄이기 위해 3장 정도씩 권장.
    """

    batch_files = image_files[start:end]

    batch_dir = OUTPUT_DIR / f"batch_{start}_{end}"

    if batch_dir.exists():
        shutil.rmtree(batch_dir)

    batch_dir.mkdir(parents=True, exist_ok=True)

    results = []

    print(f"처리 범위: {start}번 ~ {end-1}번")
    print("처리 이미지 수:", len(batch_files))

    for image_path in tqdm(batch_files):
        try:
            result = process_one_image_circle(
                image_path=image_path,
                save_dir=batch_dir
            )
            results.append(result)

        except Exception as e:
            results.append({
                "filename": Path(image_path).name,
                "path": str(image_path),
                "error": str(e)
            })

        gc.collect()

    df_batch = pd.DataFrame(results)

    csv_path = batch_dir / f"batch_{start}_{end}_results.csv"
    df_batch.to_csv(csv_path, index=False, encoding="utf-8-sig")

    zip_base = f"/content/batch_{start}_{end}_circle_results"
    zip_path = f"{zip_base}.zip"

    if Path(zip_path).exists():
        Path(zip_path).unlink()

    shutil.make_archive(
        base_name=zip_base,
        format="zip",
        root_dir=str(batch_dir)
    )

    print("배치 처리 완료")
    print("CSV:", csv_path)
    print("ZIP:", zip_path)

    return df_batch, csv_path, zip_path

df_test, csv_test, zip_test = run_batch(2, 3)
df_test

test_circle_files = sorted(list((OUTPUT_DIR / "batch_0_1" / "circle_crops").glob("*.png")))
test_overlay_files = sorted(list((OUTPUT_DIR / "batch_0_1" / "overlay_check").glob("*.png")))

print("원형 crop:")
if len(test_circle_files) > 0:
    display(Image(filename=str(test_circle_files[0])))

print("overlay:")
if len(test_overlay_files) > 0:
    display(Image(filename=str(test_overlay_files[0])))

df_batch, csv_path, zip_path = run_batch(0, 3)
files.download(zip_path)

df_batch, csv_path, zip_path = run_batch(10, 20)
files.download(zip_path)

df_batch, csv_path, zip_path = run_batch(20, 30)
files.download(zip_path)

df_batch, csv_path, zip_path = run_batch(30, 40)
files.download(zip_path)

df_batch, csv_path, zip_path = run_batch(40, 50)
files.download(zip_path)

df_batch, csv_path, zip_path = run_batch(50, 60)
files.download(zip_path)

df_batch, csv_path, zip_path = run_batch(60, 70)
files.download(zip_path)

df_batch, csv_path, zip_path = run_batch(70, 76)
files.download(zip_path)

