# -*- coding: utf-8 -*-
"""전람회-spin coating Bayesian Optimization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmILIi9gMUZkPPSDwz0tmBdZQMJhEIYr
"""

!pip install scikit-optimize

from google.colab import drive
drive.mount('/content/drive')

"""가중치"""

# ============================================================
# 0. 라이브러리 설치 및 불러오기
# ============================================================

!pip install scikit-optimize -q
!pip install openpyxl -q

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
from skopt import Optimizer
from skopt.space import Integer

drive.mount("/content/drive")


# ============================================================
# 1. 파일 경로 설정
# ============================================================

# 처음 만든 기존 실험 데이터 엑셀
BASE_EXCEL_PATH = "/content/drive/MyDrive/2026 전람회 - spin coating/data/찐초기 조작.xlsx"

# 새로 실험한 데이터만 넣는 엑셀
# 처음 실행할 때 새 데이터가 없으면 None으로 둔다.
# 예: NEW_EXCEL_PATH = None
NEW_EXCEL_PATH = "/content/drive/MyDrive/2026 전람회 - spin coating/data/BO네번째찐.xlsx"

# BO 누적 데이터 저장 파일
# 기존 데이터 + 새 데이터들이 계속 합쳐져 저장된다.
MASTER_EXCEL_PATH = "/content/drive/MyDrive/2026 전람회 - spin coating/data/master_bo_data.xlsx"

# 분석 결과 저장 파일
RESULT_CSV_PATH = "/content/drive/MyDrive/2026 전람회 - spin coating/data/spincoating_bo_results.csv"
RESULT_EXCEL_PATH = "/content/drive/MyDrive/2026 전람회 - spin coating/data/bo_analyzed_results.xlsx"

SHEET_NAME = 0


# ============================================================
# 2. 실험 조건 탐색 공간 설정
# ============================================================

# 농도: 1~5 wt%
# rpm: 500~4000 rpm, 10 rpm 단위
# 시간: 10~30 s

CONCENTRATION_MIN = 1
CONCENTRATION_MAX = 5

RPM_MIN = 500
RPM_MAX = 4000
RPM_STEP = 10

TIME_MIN = 10
TIME_MAX = 30

SEARCH_SPACE = [
    Integer(CONCENTRATION_MIN, CONCENTRATION_MAX, name="concentration"),
    Integer(RPM_MIN // RPM_STEP, RPM_MAX // RPM_STEP, name="rpm_unit"),
    Integer(TIME_MIN, TIME_MAX, name="time")
]

RANDOM_STATE = 42


# ============================================================
# 3. 엑셀 불러오기 함수
# ============================================================

def load_experiment_excel(excel_path, sheet_name=0):
    """
    엑셀 파일에서 stage, 농도, rpm, 시간, CV, RNU, Gr 값을 읽어온다.

    허용 열 이름:
    - stage, Stage
    - 농도, 농도값, concentration, Concentration
    - rpm, RPM
    - 시간, 시간값, time, Time
    - CV, cv
    - RNU, rnu
    - Gr, GR, gr
    """

    if not os.path.exists(excel_path):
        raise FileNotFoundError(f"파일을 찾을 수 없습니다: {excel_path}")

    df = pd.read_excel(excel_path, sheet_name=sheet_name)

    df.columns = [str(col).strip() for col in df.columns]

    rename_dict = {
        "Stage": "stage",
        "stage": "stage",

        "농도": "concentration",
        "농도값": "concentration",
        "concentration": "concentration",
        "Concentration": "concentration",

        "RPM": "rpm",
        "rpm": "rpm",

        "시간": "time",
        "시간값": "time",
        "time": "time",
        "Time": "time",

        "CV": "CV",
        "cv": "CV",

        "RNU": "RNU",
        "rnu": "RNU",

        "Gr": "Gr",
        "GR": "Gr",
        "gr": "Gr"
    }

    df = df.rename(columns=rename_dict)

    if "stage" not in df.columns:
        df["stage"] = "initial"

    required_columns = ["stage", "concentration", "rpm", "time", "CV", "RNU", "Gr"]

    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        raise ValueError(f"엑셀 파일에 필요한 열이 없습니다: {missing}")

    df = df[required_columns].copy()

    numeric_columns = ["concentration", "rpm", "time", "CV", "RNU", "Gr"]

    for col in numeric_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.dropna(subset=numeric_columns).reset_index(drop=True)

    df["concentration"] = df["concentration"].astype(int)
    df["rpm"] = df["rpm"].astype(int)
    df["time"] = df["time"].astype(int)

    invalid_concentration = df[
        (df["concentration"] < CONCENTRATION_MIN) |
        (df["concentration"] > CONCENTRATION_MAX)
    ]

    invalid_rpm = df[
        (df["rpm"] < RPM_MIN) |
        (df["rpm"] > RPM_MAX) |
        (df["rpm"] % RPM_STEP != 0)
    ]

    invalid_time = df[
        (df["time"] < TIME_MIN) |
        (df["time"] > TIME_MAX)
    ]

    if len(invalid_concentration) > 0:
        raise ValueError(
            f"농도값이 {CONCENTRATION_MIN}~{CONCENTRATION_MAX} wt% 범위를 벗어난 행이 있습니다."
        )

    if len(invalid_rpm) > 0:
        raise ValueError(
            f"rpm 값이 {RPM_MIN}~{RPM_MAX} 범위를 벗어나거나 {RPM_STEP} rpm 단위가 아닌 행이 있습니다."
        )

    if len(invalid_time) > 0:
        raise ValueError(
            f"시간값이 {TIME_MIN}~{TIME_MAX} s 범위를 벗어난 행이 있습니다."
        )

    df["stage"] = df["stage"].astype(str)

    return df


# ============================================================
# 4. 누적 master 엑셀 갱신 함수
# ============================================================

def make_next_stage_name(master_df):
    """
    master 데이터에 이미 존재하는 bo_round 번호를 확인하고
    다음 stage 이름을 자동 생성한다.
    """

    if "stage" not in master_df.columns:
        return "bo_round_1"

    stages = master_df["stage"].astype(str).tolist()
    round_numbers = []

    for stage in stages:
        if stage.startswith("bo_round_"):
            try:
                number = int(stage.replace("bo_round_", ""))
                round_numbers.append(number)
            except ValueError:
                pass

    if len(round_numbers) == 0:
        return "bo_round_1"

    return f"bo_round_{max(round_numbers) + 1}"


def update_master_excel(
    base_excel_path,
    master_excel_path,
    new_excel_path=None,
    sheet_name=0
):
    """
    기존 데이터와 새 BO 실험 데이터를 누적하여 master 엑셀을 갱신한다.

    작동 방식:
    1. master 파일이 없으면 base 파일을 읽어서 master를 만든다.
    2. new_excel_path가 있으면 그 파일의 새 실험 데이터를 master에 추가한다.
    3. 같은 농도, rpm, 시간 조건이 중복되면 마지막 데이터를 남긴다.
    4. 갱신된 master 데이터를 반환한다.
    """

    if os.path.exists(master_excel_path):
        master_df = load_experiment_excel(master_excel_path, sheet_name)
        print("기존 master 파일을 불러왔습니다.")

    else:
        master_df = load_experiment_excel(base_excel_path, sheet_name)

        # 처음 데이터는 stage를 initial로 고정
        master_df["stage"] = "initial"

        master_df.to_excel(master_excel_path, index=False)
        print("master 파일이 없어서 base 데이터로 새로 생성했습니다.")

    if new_excel_path is None:
        print("새 데이터 파일이 지정되지 않았습니다. 기존 master 데이터만 사용합니다.")
        print(f"현재 누적 실험 수: {len(master_df)}")
        return master_df

    if not os.path.exists(new_excel_path):
        print(f"새 데이터 파일을 찾을 수 없습니다: {new_excel_path}")
        print("기존 master 데이터만 사용합니다.")
        print(f"현재 누적 실험 수: {len(master_df)}")
        return master_df

    new_df = load_experiment_excel(new_excel_path, sheet_name)

    next_stage = make_next_stage_name(master_df)

    # 새 데이터의 stage가 비어 있거나 initial이면 자동으로 bo_round_n 부여
    new_df["stage"] = new_df["stage"].astype(str)

    invalid_stage_mask = (
        new_df["stage"].isna()
        | (new_df["stage"].str.lower() == "nan")
        | (new_df["stage"].str.strip() == "")
        | (new_df["stage"].str.lower() == "initial")
    )

    new_df.loc[invalid_stage_mask, "stage"] = next_stage

    combined_df = pd.concat([master_df, new_df], ignore_index=True)

    # 같은 조건이 중복되면 마지막 데이터 유지
    combined_df = combined_df.drop_duplicates(
        subset=["concentration", "rpm", "time"],
        keep="last"
    ).reset_index(drop=True)

    combined_df.to_excel(master_excel_path, index=False)

    print("새 데이터가 master 파일에 추가되었습니다.")
    print(f"이번 추가 stage: {next_stage}")
    print(f"현재 누적 실험 수: {len(combined_df)}")
    print(f"master 저장 위치: {master_excel_path}")

    return combined_df


# ============================================================
# 5. 정규화 및 목적함수 계산 클래스
# ============================================================

class ObjectiveCalculator:
    """
    CV, RNU, Gr를 initial 데이터 기준으로 정규화하고
    J_distance, J_max를 계산한다.

    이 코드에서 J_distance는 실제 거리값이 아니라
    CV_norm, RNU_norm, Gr_norm의 1:1:1 동일 가중 평균 목적함수 J이다.

    음수 정규화값도 그대로 반영되므로,
    initial 기준 최솟값보다 개선된 조건은 J_distance가 음수로 나타날 수 있다.
    """

    def __init__(self):
        self.ranges = None

    def fit(self, initial_df):
        required_columns = ["CV", "RNU", "Gr"]
        self._check_columns(initial_df, required_columns)

        self.ranges = {}

        for col in required_columns:
            min_value = initial_df[col].min()
            max_value = initial_df[col].max()

            if max_value == min_value:
                max_value = min_value + 1e-12

            self.ranges[col] = {
                "min": min_value,
                "max": max_value
            }

    def normalize_value(self, value, col):
        if self.ranges is None:
            raise RuntimeError("먼저 fit(initial_df)을 실행해야 합니다.")

        min_value = self.ranges[col]["min"]
        max_value = self.ranges[col]["max"]

        return (value - min_value) / (max_value - min_value)

    def transform(self, df):
        required_columns = ["CV", "RNU", "Gr"]
        self._check_columns(df, required_columns)

        result_df = df.copy()

        result_df["CV_norm"] = result_df["CV"].apply(lambda x: self.normalize_value(x, "CV"))
        result_df["RNU_norm"] = result_df["RNU"].apply(lambda x: self.normalize_value(x, "RNU"))
        result_df["Gr_norm"] = result_df["Gr"].apply(lambda x: self.normalize_value(x, "Gr"))

        # ------------------------------------------------------------
        # 수정된 부분
        # ------------------------------------------------------------
        # 기존 코드:
        # result_df["J_distance"] = sqrt(CV_norm^2 + RNU_norm^2 + Gr_norm^2)
        #
        # 수정 코드:
        # CV_norm : RNU_norm : Gr_norm = 1 : 1 : 1 동일 가중치
        # 음수 정규화값도 그대로 반영한다.
        #
        # 따라서 initial 기준 최솟값보다 더 좋은 값이 나오면
        # J_distance가 음수로 나타날 수 있다.
        # ------------------------------------------------------------
        result_df["J_distance"] = (
            result_df["CV_norm"] +
            result_df["RNU_norm"] +
            result_df["Gr_norm"]
        ) / 3

        result_df["J_max"] = result_df[["CV_norm", "RNU_norm", "Gr_norm"]].max(axis=1)

        return result_df

    @staticmethod
    def _check_columns(df, required_columns):
        missing_columns = [col for col in required_columns if col not in df.columns]

        if missing_columns:
            raise ValueError(f"필수 컬럼이 없습니다: {missing_columns}")


# ============================================================
# 6. Bayesian Optimization 클래스
# ============================================================

class SpinCoatingBO:
    """
    스핀코팅 조건 최적화를 위한 Bayesian Optimization 시스템.
    """

    def __init__(self, search_space, random_state=42):
        self.search_space = search_space

        self.optimizer = Optimizer(
            dimensions=search_space,
            base_estimator="GP",
            acq_func="EI",
            random_state=random_state
        )

        self.evaluated_conditions = set()

    @staticmethod
    def rpm_to_unit(rpm):
        return int(round(rpm / RPM_STEP))

    @staticmethod
    def unit_to_rpm(rpm_unit):
        return int(rpm_unit * RPM_STEP)

    @staticmethod
    def condition_to_real_values(condition):
        concentration, rpm_unit, time = condition
        rpm = SpinCoatingBO.unit_to_rpm(int(rpm_unit))

        return [int(concentration), int(rpm), int(time)]

    def tell_dataframe(self, df):
        required_columns = ["concentration", "rpm", "time", "J_distance"]

        for col in required_columns:
            if col not in df.columns:
                raise ValueError(f"필수 컬럼이 없습니다: {col}")

        for _, row in df.iterrows():
            condition_for_bo = [
                int(row["concentration"]),
                self.rpm_to_unit(int(row["rpm"])),
                int(row["time"])
            ]

            objective_value = float(row["J_distance"])

            real_condition_tuple = (
                int(row["concentration"]),
                int(row["rpm"]),
                int(row["time"])
            )

            if real_condition_tuple not in self.evaluated_conditions:
                self.optimizer.tell(condition_for_bo, objective_value)
                self.evaluated_conditions.add(real_condition_tuple)

    def ask_unique(self, n_points=3, max_trials=200):
        recommendations = []
        recommendation_set = set()

        trials = 0

        while len(recommendations) < n_points and trials < max_trials:
            candidate_for_bo = self.optimizer.ask()
            real_candidate = self.condition_to_real_values(candidate_for_bo)
            candidate_tuple = tuple(real_candidate)

            already_evaluated = candidate_tuple in self.evaluated_conditions
            already_recommended = candidate_tuple in recommendation_set

            if not already_evaluated and not already_recommended:
                recommendations.append(real_candidate)
                recommendation_set.add(candidate_tuple)

            trials += 1

        if len(recommendations) < n_points:
            extra_conditions = self.get_random_remaining_conditions(
                n_needed=n_points - len(recommendations),
                existing_recommendations=recommendation_set
            )
            recommendations.extend(extra_conditions)

        return recommendations

    def get_random_remaining_conditions(
        self,
        n_needed,
        existing_recommendations=None,
        max_trials=10000
    ):
        if existing_recommendations is None:
            existing_recommendations = set()

        remaining = []
        trials = 0

        while len(remaining) < n_needed and trials < max_trials:
            concentration = np.random.randint(CONCENTRATION_MIN, CONCENTRATION_MAX + 1)
            rpm = random.randrange(RPM_MIN, RPM_MAX + RPM_STEP, RPM_STEP)
            time = np.random.randint(TIME_MIN, TIME_MAX + 1)

            condition = [concentration, rpm, time]
            condition_tuple = tuple(condition)

            if (
                condition_tuple not in self.evaluated_conditions
                and condition_tuple not in existing_recommendations
            ):
                remaining.append(condition)
                existing_recommendations.add(condition_tuple)

            trials += 1

        return remaining


# ============================================================
# 7. 파레토 분석 함수
# ============================================================

def is_dominated(row, others, objectives):
    for _, other in others.iterrows():
        better_or_equal_all = all(other[obj] <= row[obj] for obj in objectives)
        strictly_better_one = any(other[obj] < row[obj] for obj in objectives)

        if better_or_equal_all and strictly_better_one:
            return True

    return False


def find_pareto_front(df, objectives):
    pareto_indices = []

    for index, row in df.iterrows():
        others = df.drop(index)

        if not is_dominated(row, others, objectives):
            pareto_indices.append(index)

    return df.loc[pareto_indices].reset_index(drop=True)


def select_balanced_pareto_candidate(pareto_df):
    if pareto_df.empty:
        raise ValueError("파레토 후보가 없습니다.")

    sorted_df = pareto_df.sort_values(
        by=["J_max", "J_distance"],
        ascending=[True, True]
    )

    return sorted_df.iloc[0]


# ============================================================
# 8. 그래프 함수
# ============================================================

def plot_bo_progress(df):
    plot_df = df.reset_index(drop=True).copy()

    experiment_numbers = np.arange(1, len(plot_df) + 1)
    j_values = plot_df["J_distance"].values
    best_so_far = np.minimum.accumulate(j_values)

    plt.figure(figsize=(8, 5))
    plt.plot(experiment_numbers, j_values, marker="o", label="Measured J_distance")
    plt.plot(experiment_numbers, best_so_far, marker="s", label="Best J_distance so far")
    plt.xlabel("Experiment number")
    plt.ylabel("J_distance")
    plt.title("Bayesian Optimization Progress")
    plt.legend()
    plt.grid(True)
    plt.show()


def plot_objective_scatter(df):
    pareto_df = find_pareto_front(df, ["CV", "RNU", "Gr"])

    pairs = [
        ("CV", "RNU"),
        ("CV", "Gr"),
        ("RNU", "Gr")
    ]

    for x_col, y_col in pairs:
        plt.figure(figsize=(6, 5))
        plt.scatter(df[x_col], df[y_col], label="All conditions")
        plt.scatter(
            pareto_df[x_col],
            pareto_df[y_col],
            s=100,
            marker="s",
            label="Pareto candidates"
        )
        plt.xlabel(x_col)
        plt.ylabel(y_col)
        plt.title(f"{x_col} vs {y_col}")
        plt.legend()
        plt.grid(True)
        plt.show()


def plot_3d_pareto(df):
    pareto_df = find_pareto_front(df, ["CV", "RNU", "Gr"])

    fig = plt.figure(figsize=(8, 6))
    ax = fig.add_subplot(111, projection="3d")

    ax.scatter(
        df["CV"],
        df["RNU"],
        df["Gr"],
        label="All conditions"
    )

    ax.scatter(
        pareto_df["CV"],
        pareto_df["RNU"],
        pareto_df["Gr"],
        s=100,
        marker="s",
        label="Pareto candidates"
    )

    ax.set_xlabel("CV")
    ax.set_ylabel("RNU")
    ax.set_zlabel("Gr")
    ax.set_title("Pareto Analysis of Film Uniformity")
    ax.legend()

    plt.show()


def plot_stage_comparison(df):
    """
    stage별 J_distance 분포를 비교한다.
    초기 실험과 BO 추가 실험의 개선 여부를 보기 위한 그래프.
    """

    plt.figure(figsize=(8, 5))

    stages = df["stage"].astype(str).unique()

    data_by_stage = [
        df[df["stage"].astype(str) == stage]["J_distance"].values
        for stage in stages
    ]

    plt.boxplot(data_by_stage, labels=stages)
    plt.xlabel("Stage")
    plt.ylabel("J_distance")
    plt.title("Stage-wise Comparison of J_distance")
    plt.grid(True)
    plt.xticks(rotation=30)
    plt.show()


# ============================================================
# 9. 데이터 누적 갱신 및 불러오기
# ============================================================

experiment_df = update_master_excel(
    base_excel_path=BASE_EXCEL_PATH,
    master_excel_path=MASTER_EXCEL_PATH,
    new_excel_path=NEW_EXCEL_PATH,
    sheet_name=SHEET_NAME
)

print("\n현재 BO에 입력되는 전체 누적 실험 데이터:")
display(experiment_df)


# ============================================================
# 10. 정규화 기준 설정 및 목적함수 계산
# ============================================================

initial_df = experiment_df[
    experiment_df["stage"].astype(str).str.lower() == "initial"
]

if len(initial_df) == 0:
    print("stage가 initial인 행이 없어서 전체 데이터를 정규화 기준으로 사용합니다.")
    initial_df = experiment_df.copy()

objective_calculator = ObjectiveCalculator()
objective_calculator.fit(initial_df)

results_df = objective_calculator.transform(experiment_df)

print("\n정규화값과 목적함수 J가 계산된 결과:")
display(results_df)


# ============================================================
# 11. BO 모델 생성 및 누적 데이터 입력
# ============================================================

bo_system = SpinCoatingBO(
    search_space=SEARCH_SPACE,
    random_state=RANDOM_STATE
)

bo_system.tell_dataframe(results_df)


# ============================================================
# 12. 다음 실험 조건 추천
# ============================================================

next_conditions = bo_system.ask_unique(n_points=3)

next_conditions_df = pd.DataFrame(
    next_conditions,
    columns=["concentration", "rpm", "time"]
)

print("\nBO가 추천한 다음 실험 조건:")
display(next_conditions_df)

for i, condition in enumerate(next_conditions, start=1):
    concentration, rpm, time = condition
    print(f"{i}. 농도 = {concentration} wt%, rpm = {rpm}, 시간 = {time} s")


# ============================================================
# 13. 현재까지 J_distance 기준 최적 조건
# ============================================================

best_j_row = results_df.loc[results_df["J_distance"].idxmin()]

print("\n현재까지 J_distance 기준 최적 조건:")
print(f"stage: {best_j_row['stage']}")
print(f"농도: {best_j_row['concentration']} wt%")
print(f"rpm: {best_j_row['rpm']} rpm")
print(f"시간: {best_j_row['time']} s")
print(f"CV: {best_j_row['CV']:.4f}")
print(f"RNU: {best_j_row['RNU']:.4f}")
print(f"Gr: {best_j_row['Gr']:.4f}")
print(f"J_distance: {best_j_row['J_distance']:.4f}")
print(f"J_max: {best_j_row['J_max']:.4f}")


# ============================================================
# 14. 파레토 최적 후보 분석
# ============================================================

pareto_df = find_pareto_front(results_df, ["CV", "RNU", "Gr"])

print("\n파레토 최적 후보:")
display(pareto_df)

best_pareto_row = select_balanced_pareto_candidate(pareto_df)

print("\n파레토 후보 중 최종 균형 조건:")
print(f"stage: {best_pareto_row['stage']}")
print(f"농도: {best_pareto_row['concentration']} wt%")
print(f"rpm: {best_pareto_row['rpm']} rpm")
print(f"시간: {best_pareto_row['time']} s")
print(f"CV: {best_pareto_row['CV']:.4f}")
print(f"RNU: {best_pareto_row['RNU']:.4f}")
print(f"Gr: {best_pareto_row['Gr']:.4f}")
print(f"J_distance: {best_pareto_row['J_distance']:.4f}")
print(f"J_max: {best_pareto_row['J_max']:.4f}")


# ============================================================
# 15. 결과 저장
# ============================================================

results_df.to_csv(RESULT_CSV_PATH, index=False, encoding="utf-8-sig")
results_df.to_excel(RESULT_EXCEL_PATH, index=False)

NEXT_RECOMMENDATION_PATH = "/content/drive/MyDrive/2026 전람회 - spin coating/data/next_bo_recommendations.xlsx"
next_conditions_df.to_excel(NEXT_RECOMMENDATION_PATH, index=False)

print("\n결과 저장 완료")
print(f"누적 원자료 master: {MASTER_EXCEL_PATH}")
print(f"분석 결과 CSV: {RESULT_CSV_PATH}")
print(f"분석 결과 Excel: {RESULT_EXCEL_PATH}")
print(f"다음 추천 조건 Excel: {NEXT_RECOMMENDATION_PATH}")


# ============================================================
# 16. 그래프 출력
# ============================================================

plot_bo_progress(results_df)
plot_objective_scatter(results_df)
plot_3d_pareto(results_df)
plot_stage_comparison(results_df)